// ============================================================
// VEXILLUM — Heraldic Icon Catalogue
// Sourced from DrawShield (GPL v3) — drawshield.net
// SVGs fetched on-demand from:
// https://raw.githubusercontent.com/JackEBoy95/vexillum-heraldic/main/charges/
// ============================================================

const HERALDIC_BASE_URL = 'https://raw.githubusercontent.com/JackEBoy95/vexillum-heraldic/main/charges/';

const HERALDIC_CATEGORIES = [
  { id: 'lion', name: 'Lions', icons: ['lion', 'lion-cadent', 'lion-couchant', 'lion-courant', 'lion-coward', 'lion-dormant', 'lion-guardant', 'lion-head', 'lion-head-affronty', 'lion-head-caboshed', 'lion-head-erased', 'lion-head-guardant', 'lion-head-jessant', 'lion-head-reguardant', 'lion-leg', 'lion-leg-couped', 'lion-leg-erased', 'lion-of-st-mark-guardant-rampant', 'lion-passant', 'lion-passant-guardant', 'lion-passant-reguardant', 'lion-rampant', 'lion-rampant-guardant', 'lion-rampant-reguardant', 'lion-rampant-tail-forked', 'lion-rampant-tail-forked-saltire', 'lion-rampant-tail-forked-saltire-reversed', 'lion-rampant-tail-nowed', 'lion-reguardant', 'lion-salient', 'lion-salient-tail-nowed', 'lion-sejant', 'lion-sejant-affronty', 'lion-sejant-erect', 'lion-sejant-guardant', 'lion-sejant-reguardant', 'lion-serpent', 'lion-statant', 'lion-statant-guardant', 'lion-vulned', 'lion-winged-passant', 'lion-winged-passant-reguardant', 'lion-winged-salient', 'lion-winged-segreant', 'snow-lion'] },
  { id: 'eagle', name: 'Eagles', icons: ['alerion', 'alerion-displayed', 'alerion-displayed-towards-base', 'eagle', 'eagle-claw', 'eagle-closed', 'eagle-displayed', 'eagle-double-headed', 'eagle-double-headed-kleestengel', 'eagle-foot', 'eagle-head', 'eagle-head-couped', 'eagle-head-erased', 'eagle-kleestengel', 'eagle-leg', 'eagle-natural', 'eagle-of-saladin', 'eagle-rising', 'eagle-rising-elevated', 'eagle-striking', 'german-eagle', 'harpy-eagle'] },
  { id: 'cross', name: 'Crosses', icons: ['asterix-cross', 'bulgarian-orthodox', 'calatrava', 'calvary', 'calvary-1', 'calvary-2', 'calvary-3', 'calvary-4', 'calvary-5', 'calvary-6', 'calvary-7', 'calvary-8', 'calvary-9', 'celtic', 'celtic-equal-armed', 'christogram', 'cossack', 'couped', 'cross', 'cross-crosslet-pattee', 'cross-doubled-elonger', 'cross-papieski', 'cross-russian', 'egyptian', 'juncyk-cross', 'long', 'lorraine', 'lorraine-branched', 'marian-cross', 'papal', 'paternoster', 'patriarchal', 'patriarchal-1', 'patriarchal-2', 'patriarchal-3', 'patriarchal-4', 'patriarchal-5', 'patriarchal-6', 'patriarchal-7', 'patriarchal-8', 'patriarchal-9', 'peter', 'plain-cross', 'portate', 'russian', 'saltire', 'santiago', 'st-james', 'tau', 'torakrzy', 'triquetras'] },
  { id: 'crown', name: 'Crowns', icons: ['antique', 'astral', 'baron', 'crown', 'crown-of-grass', 'crown-of-mullets', 'crown-of-myrtle', 'crown-of-oak-leaves', 'duke', 'earl', 'eastern', 'edwardian', 'king-of-arms', 'loyalist', 'marquis', 'mural', 'mural-city', 'mural-fancy', 'mural-provincial', 'mural-regional', 'mural-town', 'mural-village', 'naval', 'open-crown', 'palisado', 'saxon', 'vallary', 'viscount'] },
  { id: 'dragon', name: 'Dragons', icons: ['chinese-dragon', 'chinese-dragon-in-annulo', 'chinese-dragon-passant', 'dragon', 'dragon-couchant', 'dragon-displayed', 'dragon-dormant', 'dragon-head', 'dragon-head-caboshed', 'dragon-head-couped', 'dragon-head-erased', 'dragon-in-annulo', 'dragon-passant', 'dragon-rampant', 'dragon-segreant', 'dragon-sejant', 'dragon-sejant-affronty', 'dragon-statant', 'dragon-volant', 'dragon-wingless-couchant', 'dragon-wingless-passant', 'japanese-dragon', 'smoke-dragon', 'tribal-dragon', 'welsh-dragon', 'welsh-dragon-rampant', 'wyvern', 'wyvern-displayed', 'wyvern-old', 'wyvern-rampant', 'wyvern-sejant', 'wyvern-sejant-displayed', 'wyvern-sejant-forepaw-raised', 'wyvern-tail-nowed'] },
  { id: 'mythical', name: 'Mythical', icons: ['allocamelus-statant', 'alphyn-passant', 'alphyn-rampant', 'amphiptere', 'bagwyn', 'basilisk', 'basilisk-sejant', 'basilisk-wingless', 'basilisk-wings-displayed', 'bog-beast', 'calygreyhound', 'centaur', 'centaur-passant-reguardant', 'cerberus', 'cerberus-snake-tail', 'chatloup', 'chatloup-winged-sejant', 'chimera', 'cockatrice', 'cockatrice-sejant', 'devil', 'enfield-passant', 'enfield-rampant', 'fishtail-griffin', 'frauenadler', 'gorgon-head', 'gorgon-head-caboshed', 'gorgon-head-couped', 'griffin', 'griffin-couchant', 'griffin-head', 'griffin-head-erased', 'griffin-passant', 'griffin-rampant', 'harpy', 'harpy-rising', 'hydra', 'hydra-passant', 'keythong', 'keythong-head', 'keythong-head-erased', 'lamia', 'manticore', 'melusine', 'mermaid', 'mermaid-in-her-modesty', 'mermaid-in-her-vanity', 'merman', 'minotaur', 'musimon', 'ounce', 'ounce-head-caboshed', 'ounce-head-jessant', 'ounce-passant', 'ounce-passant-guardant', 'ounce-sejant', 'ounce-statant-reguardant', 'ouroboros', 'pantheon', 'pantheon-couchant', 'pantheon-courant', 'pantheon-rampant', 'pantheon-salient', 'panther', 'panther-couchant', 'panther-head-cabossed', 'panther-passant', 'panther-rampant', 'panther-rampant-guardant', 'panther-sejant', 'panther-statant-guardant', 'pegasus', 'pegasus-courant', 'pegasus-segreant', 'pegasus-statant', 'phoenix', 'phoenix-double-headed', 'salamander', 'shahbaz', 'simurgh', 'simurgh-rising', 'sphinx', 'sphinx-egyptian', 'sphinx-greek', 'sphinx-greek-couchant', 'sphinx-greek-sejant', 'sphinx-greek-statant-guardant-addorsed', 'unicorn', 'unicorn-couchant', 'unicorn-head-couped', 'unicorn-head-erased', 'unicorn-passant', 'unicorn-rampant', 'unicorn-statant', 'unicorn-trippant', 'yale-rampant', 'ziz-passant'] },
  { id: 'bird', name: 'Birds', icons: ['auk', 'bat', 'bat-sejant', 'bird', 'bird-foot', 'bird-rising', 'blackbird', 'blackbird-displayed', 'chough', 'condor-displayed', 'crane', 'crane-volant', 'crane-with-stone', 'crow', 'crow-essorant', 'crow-head', 'crow-reguardant', 'crow-rising', 'dove', 'dove-displayed', 'dove-essorant', 'dove-fondant', 'dove-reguardant', 'dove-volant', 'dove-volant-affronty', 'duck', 'duck-displayed', 'duck-enraged', 'duck-foot', 'duck-naissant', 'duck-passant', 'egg', 'emu', 'feather', 'goose', 'goose-enraged', 'goose-reguardant', 'heron', 'heron-rising', 'heron-volant', 'heron-wings-displayed', 'hummingbird', 'kite', 'lapwing', 'lark', 'lark-displayed', 'lark-essorant', 'magpie', 'magpie-displayed', 'magpie-volant-en-arriere', 'martlett', 'martlett-volant', 'merlette', 'moorcock', 'nightingale', 'ostrich', 'ostrich-feather', 'ostrich-feather-bundle-3', 'owl', 'owl-affronty', 'owl-displayed', 'partridge', 'peacock', 'peacock-affronty', 'peacock-feather', 'pelican', 'pelican-natural', 'penguin', 'popinjay', 'puffin', 'quail', 'raven', 'raven-displayed', 'raven-head', 'raven-migrant', 'raven-reguardant', 'raven-rising', 'raven-rising-displayed', 'raven-striking', 'raven-volant', 'robin', 'seagull', 'seagull-volant', 'shoveller', 'starling', 'stork', 'stork-volant', 'swallow', 'swan', 'swan-displayed', 'swan-double-headed', 'swan-essorant', 'swan-head', 'swan-nageant', 'swan-naissant', 'swan-passant', 'swan-rising', 'swan-rousant', 'swan-volant', 'vulture', 'vulture-displayed', 'wing', 'wing-pair-2', 'wing-pair-2-conjoined-in-lure', 'woodcock'] },
  { id: 'animal', name: 'Animals', icons: ['anteater-rampant', 'antelope', 'antelope-head-erased', 'antelope-head-erased-affronty', 'antelope-passant', 'antelope-rampant', 'antelope-salient', 'antelope-statant', 'armadillo', 'axolotl', 'bactrian-camel', 'bison', 'bison-head-affronty', 'bison-head-caboshed', 'bison-passant-guardant', 'bison-rampant', 'bison-statant', 'camel', 'camel-couchant', 'camel-passant', 'camel-rampant', 'camel-statant', 'camelopard', 'camelopard-dormant', 'camelopard-passant', 'camelopard-rampant', 'camelopard-statant', 'camelopard-winged', 'capybara', 'chameleon', 'crocodile', 'crocodile-rampant', 'elephant', 'elephant-head', 'elephant-head-caboshed', 'elephant-head-couped', 'elephant-head-erased', 'elephant-passant', 'elephant-rampant', 'elephant-tower-back', 'frog', 'frog-couchant', 'frog-rampant', 'frog-salient', 'frog-sejant', 'frog-sejant-affronty', 'gorilla', 'gorilla-statant', 'hippo', 'hyena', 'jerboa', 'kangaroo-salient', 'leopard', 'leopard-head', 'leopard-head-jessant', 'leopard-natural', 'leopard-natural-statant', 'leopard-natural-statant-reguardant', 'leopard-passant', 'leopard-passant-guardant', 'leopard-sejant', 'leopard-statant-reguardant', 'lizard-rampant', 'lizard-statant', 'llama', 'llama-head-couped', 'llama-head-erased', 'llama-passant', 'llama-statant', 'lynx-head-couped', 'lynx-head-erased', 'lynx-passant', 'lynx-rampant', 'lynx-statant', 'lynx-statant-coward', 'monkey', 'monkey-head', 'monkey-head-caboshed', 'monkey-passant', 'monkey-rampant', 'monkey-sejant', 'monkey-sejant-erect-collared', 'monkey-winged-passant', 'monkey-winged-rising', 'moose', 'moose-head', 'opossum-rampant', 'paw-print', 'porcupine', 'raccoon', 'raccoon-head-caboshed', 'raccoon-rampant', 'raccoon-rampant-guardant', 'reindeer', 'reindeer-head', 'reindeer-lodged', 'reindeer-rampant', 'reindeer-salient', 'reindeer-trippant', 'rhinoceros', 'rhinoceros-couchant', 'rhinoceros-rampant', 'scorpion', 'tiger', 'tiger-courant', 'tiger-head-couped', 'tiger-natural', 'tiger-natural-couchant', 'tiger-natural-head-cabossed', 'tiger-natural-head-erased', 'tiger-natural-passant', 'tiger-natural-rampant', 'tiger-natural-statant', 'tiger-passant', 'tiger-rampant', 'tiger-salient', 'tiger-salient-reguardant', 'tiger-sejant', 'tiger-sejant-erect', 'tiger-statant', 'toad', 'tortoise', 'wolverine-rampant', 'wolverine-statant', 'zebra'] },
  { id: 'flower', name: 'Flowers', icons: ['belladona', 'borage', 'cinquefoil', 'columbine', 'cornflower', 'crocus', 'daffodil', 'daisy', 'daisy-flower', 'dandelion', 'dandelion-leaf', 'eidelweiss-flower', 'forget-me-not', 'foxglove', 'geranium', 'gillyflower', 'gillyflower-stemmed', 'iris', 'jasmine', 'jasmine-flower', 'lavender', 'lilac-sprig', 'lily', 'lily-of-the-valley', 'lily-pad', 'lotus', 'lotus-in-profile', 'magnolia', 'octofoil', 'peony', 'periwinkle-flower', 'poppy', 'quatrefoil', 'rose', 'rose-leaf', 'rose-natural', 'rose-sprig', 'rose-stem', 'rue-flower', 'rue-sprig', 'sexfoil', 'shamrock', 'strawberry-flower', 'strawberry-plant', 'sunflower', 'trefoil', 'trillium', 'tulip', 'tulip-bundle-3', 'violet', 'wood-sorrel-flower'] },
  { id: 'celestial', name: 'Celestial', icons: ['comet', 'estoile-inflamed', 'estoile-of6', 'estoile-of8', 'moon', 'moon-crescent', 'moon-decrescent', 'moon-increscent', 'moon-natural', 'moon-pendant', 'rainbow', 'sun', 'sun-in-glory', 'sun-outline', 'sun-rays', 'sunburst', 'thunderbolt'] },
  { id: 'astronomical', name: 'Astronomical', icons: ['earth', 'jupiter', 'mars', 'mercury', 'moon', 'neptune', 'pluto', 'saturn', 'sun', 'uranus', 'venus'] },
  { id: 'geometric', name: 'Geometric', icons: ['bbox', 'bezant', 'billet', 'cartouche', 'chevron', 'chevron-couped', 'crescent', 'crescent-pendent', 'delf', 'delf-ploye', 'fret', 'fusil', 'golpe', 'goutte', 'guze', 'hexagon', 'hexagon-pierced', 'hexagon-voided', 'hurt', 'icicle', 'icosahedron', 'lozenge', 'lozenge-pierced', 'lozenge-voided', 'mascle', 'mascle-ploye', 'octagon', 'octagon-pierced', 'octagon-voided', 'orange', 'pellet', 'penrose-triangle', 'pentagon', 'pentagon-pierced', 'pentagon-voided', 'pomme', 'rectangle', 'roundel', 'rustre', 'shakefork', 'square', 'square-pierced', 'square-voided', 'torteau', 'triangle', 'triangle-pierced', 'triangle-voided', 'triskele', 'valknut'] },
  { id: 'weapon', name: 'Weapons', icons: ['archery-target', 'arquebus', 'battering-ram', 'bow', 'bow-with-arrow', 'bow-with-arrow-nocked', 'caltrap', 'cannon', 'catherine-wheel', 'club', 'cranequin', 'cronel', 'crossbow', 'flail', 'flintlock-pistol', 'glaive', 'hand-cannon', 'heraldic-catapult', 'lance', 'lance-fracted', 'mace', 'mace-flanged', 'musket', 'partisan', 'petronel', 'pole-cannon', 'quintain', 'scaling-ladder', 'shackle', 'staff', 'staff-palmer', 'staff-ragged', 'staff-wreathed', 'tilting-spear', 'truncheon', 'tryzub', 'war-hammer', 'war-wagon'] },
  { id: 'sword', name: 'Swords', icons: ['arming-sword', 'bowie-knife', 'broken-sword', 'claymore', 'cutlass', 'dagger', 'falchion', 'katana', 'rapier', 'sabre', 'scabbard', 'seax', 'shamshir', 'sword-cortana', 'sword-fracted', 'sword-in-its-sheath', 'swordstpaul'] },
  { id: 'armour', name: 'Armour', icons: ['bracer', 'breastplate', 'camail', 'carbuncle', 'chamfron', 'charge-torse', 'cuisse', 'elbow-guard', 'gauntlet', 'gauntlet-aversed', 'gauntlet-clenched', 'helmet-baronet', 'helmet-closed', 'helmet-corinthian', 'helmet-esquire', 'helmet-great', 'helmet-great-affronty', 'helmet-great-winged', 'helmet-horned', 'helmet-knight', 'helmet-knight-affronty', 'helmet-knight-closed', 'helmet-norman', 'helmet-ocular', 'helmet-peer', 'helmet-royal', 'helmet-turkish', 'mail-shirt', 'mailed-fist', 'morion', 'pauldron', 'quintain', 'solleret'] },
  { id: 'ship', name: 'Ships', icons: ['anchor', 'anchor-fouled', 'barge', 'caravel', 'coracle', 'crows-nest', 'fishing-boat', 'galley', 'harpoon', 'lymphad', 'lymphad-furled', 'lymphad-furled-oars-in-action', 'lymphad-sails-set', 'lymphad-sails-set-oars-in-action', 'mariners-compass', 'mariners-whistle', 'oar', 'oar-insaltire-2', 'rowboat', 'rudder', 'rudder-pole', 'sail', 'salmon-spear', 'ship', 'ships-wheel', 'trireme'] },
  { id: 'architecture', name: 'Architecture', icons: ['anille', 'arch', 'arch-double', 'army-tent', 'bascule', 'bridge', 'bridge-of-five-arches', 'bridge-of-four-arches', 'bridge-of-one-arch', 'bridge-of-three-arches', 'bridge-of-two-arches', 'bridge-three-arches', 'bridge-two-arches', 'castle', 'castle-towered', 'castle-triple-towered', 'church', 'city', 'cogwheel', 'cornice', 'cornice-four-lobed', 'door', 'door-bolt', 'drawbridge', 'fountain-natural', 'fountain-stone', 'gate', 'house', 'keystone', 'keystone-couped', 'lighthouse', 'lock-plate', 'millwheel', 'obelisk', 'pavilion', 'pennon', 'pennsylvania-keystone', 'pillar', 'portcullis', 'pyramid', 'tower', 'tower-triple-towered', 'truss', 'watchtower', 'waterwheel', 'well', 'window'] },
  { id: 'christian', name: 'Christian', icons: ['altar', 'angel', 'angel-kneeling', 'angel-volant', 'ark-of-the-covenant', 'cherub', 'church-bell', 'crown-of-thorns', 'crozier', 'crucifix', 'mitre', 'paschal-lamb', 'passion-nail', 'rosary', 'seraph', 'sleeping-cherub', 'virgin'] },
  { id: 'knot', name: 'Knots', icons: ['agemaki-knot', 'bowen-knot', 'carolingian-knot', 'celtic-knot', 'cord', 'de-lacy-knot', 'heneage-knot', 'hungerford-knot', 'knot', 'lovers-knot', 'quatrefoil-knot', 'savoy-knot', 'solomons-knot', 'stafford-knot', 'suffolk-knot', 'trefoil-knot', 'trinity-knot', 'wake-knot'] },
  { id: 'zodiac', name: 'Zodiac', icons: ['aquarius', 'aries', 'cancer', 'capricorn', 'female', 'gemini', 'leo', 'libra', 'male', 'pisces', 'sagittarius', 'scorpio', 'taurus', 'virgo'] },
  { id: 'human', name: 'Human', icons: ['archer', 'arm', 'arm-couped', 'arm-cubit', 'arm-cubit-armoured', 'arm-cubit-habited', 'arm-embowed', 'arm-embowed-armoured', 'arm-habited', 'beard', 'blacksmith', 'bone', 'dextrochere', 'eye', 'fallen-knight-embowed', 'fist', 'foi', 'fool-head', 'foot', 'foot-winged', 'footprint', 'hand', 'hand-benediction', 'hand-clawed', 'hand-couped', 'hand-erased', 'hand-of-benediction', 'hand-pair-2', 'hand-pair-2-clasped', 'heart', 'janus-head', 'jawbone', 'knight-mounted', 'knight-statant-affronty', 'leg', 'leg-armoured', 'maiden', 'maiden-head', 'maiden-head-bust', 'maiden-head-bust-nude', 'man-armoured', 'man-habited', 'man-head', 'man-head-bust', 'man-head-couped', 'man-nude', 'molar', 'monk', 'moor-head', 'rib-bone', 'saracen-head', 'saracen-head-erased', 'savage', 'savage-head', 'skeleton', 'skull', 'tress-of-hair', 'triskelion-of-arms', 'triskelion-of-legs-armored', 'voided-eye', 'woman', 'woman-head-couped', 'woman-nude', 'wound'] },
  { id: 'wildlife', name: 'Wildlife', icons: ['badger', 'badger-head', 'badger-head-caboshed', 'badger-head-erased', 'badger-rampant', 'beaver', 'beaver-passant', 'beaver-rampant', 'beaver-rampant-vorant-of-fish', 'beaver-salient', 'beaver-salient-vorant-of-fish', 'beaver-sejant', 'beaver-sejant-erect', 'beaver-statant', 'beaver-statant-vorant-of-fish', 'cat', 'cat-couchant', 'cat-couchant-guardant', 'cat-herisse', 'cat-passant', 'cat-passant-guardant', 'cat-rampant-reguardant', 'cat-salient', 'cat-sejant', 'cat-sejant-erect', 'cat-sejant-guardant', 'cat-sejant-reguardant', 'cat-statant', 'cat-winged-rampant', 'cat-winged-salient', 'ferret', 'fox', 'fox-couchant', 'fox-courant', 'fox-courant-reguardant', 'fox-head', 'fox-head-erased', 'fox-passant', 'fox-passant-guardant', 'fox-rampant', 'fox-rampant-guardant', 'fox-rampant-reguardant', 'fox-sejant', 'fox-sejant-guardant', 'fox-statant', 'genet', 'hedgehog', 'hedgehog-rampant', 'hedgehog-reguardant', 'hedgehog-sejant-erect', 'hedgehog-statant', 'mole', 'mole-statant', 'mouse', 'mouse-couchant', 'mouse-dormant', 'mouse-passant', 'mouse-rampant', 'mouse-sejant-erect', 'mouse-statant', 'otter', 'otter-courant', 'otter-rampant-reguardant', 'rat', 'rat-rampant', 'rat-statant', 'rat-tergiant', 'shrew', 'siberian-cat', 'snake', 'squirrel', 'squirrel-holding-nut', 'squirrel-rampant', 'squirrel-sejant', 'squirrel-sejant-holding-nut', 'squirrel-statant', 'stoat-passant', 'stoat-passant-reguardant', 'stoat-rampant', 'stoat-statant', 'weasel', 'weasel-rampant', 'wildcat', 'wildcat-head', 'wildcat-head-caboshed', 'wildcat-passant', 'wildcat-passant-guardant', 'wolf', 'wolf-couchant', 'wolf-courant', 'wolf-dormant', 'wolf-head', 'wolf-head-affronty', 'wolf-head-caboshed', 'wolf-head-couped', 'wolf-head-erased', 'wolf-head-erased-affronty', 'wolf-passant', 'wolf-passant-reguardant', 'wolf-paw-print', 'wolf-rampant', 'wolf-reguardant', 'wolf-salient', 'wolf-sejant', 'wolf-sejant-affronty', 'wolf-sejant-erect', 'wolf-sejant-ululant', 'wolf-statant'] },
  { id: 'fish', name: 'Fish & Sea', icons: ['barbel', 'barbel-embowed', 'carp-embowed', 'catfish-embowed', 'catfish-haurient-embowed', 'chabot', 'chabot-tergiant', 'eel', 'fish', 'fish-embowed', 'fish-haurient', 'fish-head', 'fish-skeleton', 'fish-winged', 'flying-fish', 'goldfish', 'herring', 'luce', 'luce-embowed', 'luce-winged', 'roach', 'roach-naissant', 'salmon', 'swordfish-haurient', 'trout', 'turbot', 'walleye'] },
  { id: 'sealife', name: 'Sea Life', icons: ['calamarie', 'calamarie-embowed', 'crab', 'crab-claw', 'crab-claw-pair-2', 'crayfish', 'dolphin', 'dolphin-embowed', 'dolphin-haurient', 'dolphin-natural', 'dolphin-winged', 'escallop', 'escallop-natural', 'ichthyocentaur', 'killer-whale', 'lobster', 'lobster-claw', 'manatee', 'narwhal', 'polypus', 'prawn', 'sea-bear', 'sea-dog', 'sea-dragon', 'sea-fox', 'sea-fox-guardant', 'sea-goat', 'sea-horse', 'sea-horse-natural', 'sea-lion', 'sea-lion-embowed', 'sea-otter', 'sea-serpent', 'sea-serpent-erect', 'sea-serpent-ondoyant', 'sea-tortoise-natural', 'sea-turtle', 'sea-wolf', 'shark', 'shrimp', 'swordfish', 'triton-trumpet', 'turtle', 'walrus', 'whale', 'whale-embowed', 'whale-embowed-spouting', 'whale-spouting', 'whelk', 'zydrach'] },
  { id: 'plant', name: 'Plants', icons: ['acanthus-leaf', 'acorn', 'acorn-slipped-leaved', 'acorn-sprig', 'aloe-vera', 'bamboo', 'bullrush', 'bush', 'cactus', 'clover', 'clover-leaf', 'grape-bundle-3', 'grape-leaf', 'heather', 'ivy-leaf', 'ivy-vine', 'ivy-wreath', 'mandrake', 'nettle-leaf', 'pineapple', 'reed', 'reed-bundle-3', 'seeblatt', 'thistle', 'tobacco-sprig', 'vine', 'vine-leaf', 'wheat-bundle-3', 'wheat-ear', 'wheat-stalk'] },
  { id: 'tree-fruit', name: 'Trees & Fruit', icons: ['alder-tree', 'almond', 'apple', 'apple-slipped-leaved', 'apple-sprig', 'apple-tree', 'ash-sprig', 'ash-tree-eradicated', 'aspen-leaf', 'aspen-tree', 'banana', 'banana-stem', 'beech-sprig', 'birch-leaf', 'birch-tree', 'blackberry-sprig', 'broom-sprig', 'cedar-tree', 'cherry-blossom', 'cherry-pair-2', 'cherry-sprig', 'chestnut-tree', 'chrysanthemum', 'chrysanthemum-leaf', 'conker', 'cypress-tree', 'dogwood-blossom', 'elder-blossom', 'elder-sprig', 'elder-sprig-fructed', 'fig-leaf', 'fig-tree', 'fir-tree', 'flax-blossom', 'hazel-sprig', 'hazelnut', 'holly-leaf', 'holly-sprig', 'hop-cone', 'juniper-sprig', 'lady-mantle-leaf', 'laurel-bough-fructed', 'laurel-leaf', 'laurel-sprig-fructed', 'lemon', 'lemon-slipped-leaved', 'lime-leaf', 'linden-leaf', 'linden-sprig', 'linden-tree', 'linden-tree-eradicated', 'log', 'maple-leaf', 'maple-leaf-conjoined-3', 'maple-seed', 'marijuana-leaf', 'oak', 'oak-leaf', 'oak-sprig-fructed', 'oak-tree', 'oak-tree-eradicated', 'olive', 'olive-sprig-fructed', 'orange-flower', 'orange-tree', 'palm-leaf', 'palm-leaf-insaltire-2', 'palm-tree', 'palm-tree-insaltire-2', 'pear', 'pear-tree', 'pine-cone', 'pine-new-england-tree', 'pine-scots-tree', 'pine-scots-tree-eradicated', 'pine-tree', 'pine-tree-eradicated', 'pineapple', 'plane-tree', 'pomegranate', 'poplar-leaf', 'quince', 'rowan-leaf', 'rowan-tree', 'rowan-tree-eradicated', 'strawberry', 'strawberry-leaf', 'tree', 'tree-blasted', 'tree-blasted-eradicated', 'tree-eradicated', 'tree-stump-eradicated', 'trees-hurst-of-couped', 'walnut', 'werewood-tree', 'willow-tree', 'withered-tree', 'yew-tree'] },
  { id: 'livestock', name: 'Livestock', icons: ['ass', 'ass-head', 'ass-head-caboshed', 'ass-head-couped', 'ass-head-erased', 'ass-passant', 'ass-rampant', 'bull', 'bull-head', 'bull-head-caboshed', 'bull-head-couped', 'bull-head-erased', 'bull-passant', 'bull-passant-guardant', 'bull-rampant', 'bull-rampant-guardant', 'bull-salient', 'bull-sejant', 'bull-statant', 'bull-statant-guardant', 'bull-winged', 'calf', 'cock', 'cock-double-headed', 'cock-head', 'cock-head-couped', 'cock-head-erased', 'cock-rising', 'cow', 'cow-head', 'egg', 'goat', 'goat-clymant', 'goat-courant', 'goat-head', 'goat-head-affronty', 'goat-head-erased', 'goat-passant', 'goat-salient', 'goat-statant', 'hen', 'horse', 'horse-courant', 'horse-head', 'horse-head-erased', 'horse-passant', 'horse-passant-reguardant', 'horse-rampant', 'horse-rampant-reguardant', 'horse-salient', 'horse-statant', 'lamb', 'ox', 'pig', 'ram', 'ram-clymant', 'ram-head-caboshed', 'ram-head-couped', 'ram-head-erased', 'ram-passant', 'ram-statant', 'rams-horn', 'sheep', 'sheep-couchant', 'sheep-head-couped', 'sheep-passant', 'sheep-passant-reguardant', 'sheep-rampant', 'sheep-salient', 'sheep-statant', 'sheep-statant-guardant', 'sow-head-couped', 'sow-head-erased', 'sow-passant', 'sow-rampant', 'sow-statant', 'sow-winged-rampant', 'testicules', 'testicules-pair-2', 'turkeycock'] },
  { id: 'serpent', name: 'Serpents', icons: ['cobra', 'pithon-erect-affronty', 'pithon-volant', 'serpent', 'serpent-entwined-with-pillar', 'serpent-erect', 'serpent-erect-tail-nowed', 'serpent-erect-vorant-a-child', 'serpent-in-annulo', 'serpent-nowed', 'snake', 'snake-glissant', 'snake-passant'] },
  { id: 'insect', name: 'Insects', icons: ['ant', 'bee', 'beetle', 'butterfly', 'butterfly-natural', 'butterfly-statant', 'cicada', 'cricket', 'dragonfly', 'fly', 'grasshopper', 'hornet', 'ladybird', 'moth', 'slug', 'snail', 'spider', 'spiderweb', 'stag-beetle', 'wasp'] },
  { id: 'tools', name: 'Tools', icons: ['adze', 'angles', 'angles-pair-of', 'anvil', 'astrolabe', 'auger', 'awl', 'barnacle', 'billhook', 'block-tackle', 'brazier', 'brey', 'brey-expanded', 'calipers', 'calipers-pair-2', 'chain', 'chisel', 'closing-nail', 'compass', 'cramp', 'cramp-bundle-3', 'cramp-pair-2', 'drawknife', 'drill', 'fleam', 'float', 'forge-hammer', 'furnace', 'grindstone', 'hammer', 'hand-saw', 'hempbrake', 'hod', 'hoe', 'key', 'key-pair-2', 'ladder', 'mallet', 'mattock', 'millrind', 'padlock', 'plane', 'pliers', 'pliers-pair-2', 'plummet', 'punner', 'quadrant', 'rake', 'ring-of-keys', 'royne', 'saw-blade', 'saw-frame', 'scales', 'scythe', 'set-square', 'shacklebolt', 'shovel', 'sledge-hammer', 'soldering-iron', 'spade', 'staple', 'trestle', 'trowel', 'vernier-calipers', 'wolfiron'] },
  { id: 'crafts', name: 'Crafts', icons: ['aiguille', 'artist-palette', 'artists-brush', 'barber-pole', 'bobbin-lace', 'bookbinding-press', 'caligraphy-knife', 'distaff', 'embroiderers-broach', 'heckle', 'needle', 'needle-threaded', 'quill-pen', 'ribbon', 'scissors', 'scissors-pair-2', 'shears', 'shears-pair-2', 'shuttle', 'spindle', 'thimble', 'thread-spool', 'yarn-ball', 'yarn-quill', 'yarn-swift'] },
  { id: 'alchemical', name: 'Alchemical', icons: ['air', 'copper', 'earth', 'fire', 'gold', 'iron', 'mercury', 'salt', 'sulphur', 'tin', 'water'] },
  { id: 'emblem', name: 'Emblems', icons: ['ankh', 'ashoka-chakra', 'badge-of-clan-ross', 'bashkir-quray-flower', 'bashkir-quray-flower-stemmed', 'baton-marshall', 'bowl-of-hygeia', 'caduceus', 'chain-of-navarre', 'chain-of-navarre-square', 'chaplet', 'chi-rho', 'cornucopia', 'dharma-wheel', 'ermine-spot', 'fasces', 'fer-a-loup', 'fleur-de-lys', 'fleur-de-lys-double', 'fleur-de-lys-double-fancy', 'fleur-de-lys-fancy', 'fleur-de-lys-florence', 'fleur-de-lys-quebec', 'hammer-and-sickle', 'heralds-staff', 'khanda', 'labyrinth', 'lauburu', 'laurel-wreath', 'laurel-wreath-fructed', 'lion-of-st-marks', 'lion-of-st-marks-with-sword', 'lozenge-ploye', 'lozenge-pometty', 'mascle-ploye', 'masculyn', 'menorah-of-7', 'menorah-of-9', 'mitsutomoe', 'nesselblatt', 'oda-emblem', 'pall-bottony', 'pentacle', 'pentagram', 'question-mark', 'rod-of-esclapius', 'rogacina-crossed-and-fourchy', 'rogacina-double-crossed', 'rogacina-double-pointed', 'rogacina-issuant-from-a-cauldron', 'rogacina-issuant-from-a-demi-annulet', 'rogacina-issuant-from-a-moustache', 'star-of-david', 'tai-chi', 'thyrsus', 'tortoise-shell-plate', 'triple-moon', 'triquetra', 'triskele', 'triskelion', 'triskelion-armoured', 'triskelion-of-spirals', 'triskelion-pometty', 'umebachi', 'vair-bell', 'vair-spot', 'winged-heart', 'zule'] },
];

// In-memory cache for fetched SVGs
const _heraldicCache = new Map();

async function fetchHeraldicSvg(category, slug) {
  const key = `${category}/${slug}`;
  if (_heraldicCache.has(key)) return _heraldicCache.get(key);
  try {
    const res = await fetch(`${HERALDIC_BASE_URL}${category}/${slug}.svg`);
    if (!res.ok) throw new Error('404');
    const text = await res.text();
    _heraldicCache.set(key, text);
    return text;
  } catch(e) {
    return null;
  }
}
